# Generated by Django 5.0.4 on 2024-05-09 01:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threat_solutions_app", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="risktreatment",
            name="safeguard",
        ),
        migrations.AddField(
            model_name="safeguard",
            name="treatment",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="safeguards",
                to="threat_solutions_app.risktreatment",
            ),
        ),
        migrations.AlterField(
            model_name="safeguard",
            name="threats",
            field=models.ManyToManyField(
                blank=True, related_name="safeguards", to="threat_solutions_app.threat"
            ),
        ),
    ]
