# Generated by Django 5.0.4 on 2024-04-25 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0002_stage_assessment_questions"),
    ]

    operations = [
        migrations.AlterField(
            model_name="userassessment",
            name="role",
            field=models.CharField(
                choices=[
                    ("owner", "Owner"),
                    ("admin", "Administrator"),
                    ("sitelead", "Site Leader"),
                    ("analyst", "Analyst"),
                    ("collaborator", "Collaborator"),
                    ("guest", "Guest"),
                ],
                max_length=50,
            ),
        ),
    ]
