# Generated by Django 5.0.4 on 2024-04-26 03:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0003_alter_userassessment_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentquestion",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="questions",
                to="assessment_app.assessment",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresponse",
            name="assessment_question",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessment_app.assessmentquestion",
            ),
        ),
        migrations.AlterField(
            model_name="assessmentresponse",
            name="user_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="responses",
                to="assessment_app.userassessment",
            ),
        ),
        migrations.AlterField(
            model_name="userassessment",
            name="assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="user_assessments",
                to="assessment_app.assessment",
            ),
        ),
        migrations.AlterField(
            model_name="userassessmentpermission",
            name="user_assessment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="permissions",
                to="assessment_app.userassessment",
            ),
        ),
    ]
