# Generated by Django 5.0.4 on 2024-04-26 19:28

import assessment_app.models
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0005_assessmentquestioncollection_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessment",
            name="collection",
            field=models.ForeignKey(
                default=assessment_app.models.get_default_collection,
                help_text="The collection used for this assessment.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="assessments",
                to="assessment_app.assessmentquestioncollection",
            ),
        ),
    ]
