# Generated by Django 5.0.4 on 2024-04-26 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0006_assessment_collection"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestion",
            name="question_help_text",
            field=models.TextField(default="Help Text"),
            preserve_default=False,
        ),
    ]
