# Generated by Django 5.0.4 on 2024-05-05 05:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0007_assessmentquestion_question_help_text"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestioncollection",
            name="is_active",
            field=models.BooleanField(
                blank=False, default=False
            ),
            preserve_default=False,
        ),
    ]
