# Generated by Django 5.0.4 on 2024-05-05 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0008_assessmentquestioncollection_is_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="assessmentquestion",
            name="question_section",
            field=models.TextField(default="None"),
        ),
        migrations.AlterField(
            model_name="assessmentquestioncollection",
            name="is_active",
            field=models.BooleanField(blank=True),
        ),
    ]
