# Generated by Django 5.0.4 on 2024-05-05 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("assessment_app", "0009_assessmentquestion_question_section_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="assessmentquestion",
            name="question_section",
            field=models.CharField(default="None", max_length=10),
        ),
    ]
